### ISSUE TITLE
Plugin to update a real Teeworlds or DDNet server (a simple /reload command sent should be enough)

### ISSUE THREAD

**Issue by ChillerDragon** [k2d222/twwe#39]
From the roadmap.

@k2d222 in case you do not know already. Teeworlds servers have something called econ and ddnet servers have fifo. So this is just sending the string `reload` via econ (think of it as telnet) or fifo. So there could be just a config in the env file what the fifo file is or what the econ ip/port/password is. And then a request is made on save.

Who would be responsible for that? I assume the server not the client right?

Is it planned that people use your instance and then give you access to their servers? Or are the credentials just staying in the front end and a fetch request from js is triggering the reload for the server the user configured in the UI? Or does everyone host his own twwe backend paird with a teeworlds server?

**Comment by k2d222** [comment]
> Who would be responsible for that? I assume the server not the client right?

Yes, the server. I experimented yesterday with that:
```fish
while inotifywait -e modify <path/to/edited/map.map>
    echo "reload" > server.fifo 
end
```
And that did the trick. I think a .env variable to the fifo file is the easiest to implement right now.

> Is it planned that people use your instance and then give you access to their servers? Or are the credentials just staying in the front end and a fetch request from js is triggering the reload for the server the user configured in the UI? Or does everyone host his own twwe backend paird with a teeworlds server?

3rd solution, host both twwe and tw server. I don't plan on hosting twwe for the whole world right now, but we'll see where the project goes. I think tough a button `reload server` could be nice in the ui instead of triggering the reload on each map save.
