### ISSUE TITLE
Join button for private maps is broken

### ISSUE THREAD

**Issue by ChillerDragon** [k2d222/twwe#79]
On https://tw.thissma.fr/ clicking the "Join" button in the access key menu does nothing for me.

![image](https://github.com/user-attachments/assets/b1d62c27-6136-4ec4-8b89-72b23b1e7ebe)

(throws a 502 Bad Gateway in the network tab)

Going to the /edit path manually works.

**Comment by ChillerDragon** [comment]
Also the teeworlds server 82.64.235.33:8303 seems to be offline.

**Comment by k2d222** [comment]
Ooh, because that's not how it works haha (but tbf, it's not documented anywhere and the feature is not properly tested! it's the last thing I was working on before taking a break on the project) -- the project is not dead btw, just doing other stuff atm

So the Access Key feature is really cool. If you install the [standalone app](https://github.com/k2d222/twwe/releases), then you can access and edit your local maps like the built-in editor. But you can also forward them to one of the online servers (like tw.thissma.fr) So ppl can connect to your map on your computer.

Here's how it works 
![image](https://github.com/user-attachments/assets/54b8c73c-93b1-465f-84b1-ea9241fef1ba)
then select a server and an access key aka password.

Then, anyone who has the passkey can join your map.

(if you're online right now, you can try to join `together-shells-divide-mathematics`)

**Comment by k2d222** [comment]
> Also the teeworlds server 82.64.235.33:8303 seems to be offline.

Ah, I'll check on this when I get home :)

**Comment by ChillerDragon** [comment]
Ah okay I thought that was an UI way of accessing private maps. Seems like those have to be accessed with url then I see.

Cool thanks for showcasing the feature.

**Comment by k2d222** [comment]
> Also the teeworlds server 82.64.235.33:8303 seems to be offline.

@ChillerDragon back online
